export const img7 = require("./img7.jpg")
export const img8 = require("./img8.jpg")
export const img9 = require("./img9.jpg")
export const img10 = require("./img10.jpg")
export const img12 = require("./img12.jpg")